version: '3.1'

services:
  db:
    container_name: mubify-postgres
    image: postgres 
    command: postgres -c 'max_connections=800'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mubify
    volumes:
      - ./testdata/postgres:/var/lib/postgresql/data
